[package]
name = "emergency-alert"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
libpulse-binding = "2.28.2"
pulsectl-rs = "0.3.2"
rodio = "0.20.1"
